export enum ConfigItem {
    DB_STORAGE = 'DB_STORAGE',
    DB_DIALECT = 'DB_DIALECT',
    DB_USER = 'DB_USER',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_HOST = 'DB_HOST',
    DB_PORT = 'DB_PORT',
    DB_DATABASE = 'DB_DATABASE',
    AGENDA_URL = 'AGENDA_URL',
    AGENDA_COLLECTION = 'AGENDA_COLLECTION',
}
